spring:
  cloud:
    function:
      definition: comment; like; follow;
    stream:
      binders:
        kafka:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: localhost:9092
      bindings:
        comment-in-0:
          destination: comment
          content-type: application/json
          group: notification-consumer
          consumer.max-attempts: 2
          binder: kafka
        like-in-0:
          destination: like
          content-type: application/json
          group: notification-consumer
          consumer.max-attempts: 2
          binder: kafka
        follow-in-0:
          destination: follow
          content-type: application/json
          group: follow-consumer
          consumer.max-attempts: 2
          binder: kafka








